"""Evidence-backed causal taxonomy for the canonical GIADA teacher."""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any


VOLTAGE_GATED = {
    "Ca_HVA", "Ca_LVAst", "Ih", "Im", "K_Pst", "K_Tst", "Nap_Et2",
    "NaTa_t", "NaTs2_t", "SKv3_1",
}
CALCIUM_GATED = {"SK_E2"}
CONCENTRATION_DYNAMICS = {"CaDynamics_E2"}
EVENT_DRIVEN_SYNAPSES = {
    "ProbAMPANMDA2", "ProbAMPANMDA3", "ProbAMPANMDA_EMS",
    "ProbGABAAB_EMS", "ProbUDFsyn2",
}
ANALYTIC_POINT_PROCESSES = {"epsp"}


def _names(rows: list[dict[str, Any]]) -> set[str]:
    return {row["name"] for row in rows}


def _classify_mod(row: dict[str, Any]) -> dict[str, Any]:
    name = row["mechanism"]["name"]
    states = sorted(_names(row["declarations"]["state"]))
    assigned = _names(row["declarations"]["assigned"])
    ion_reads = sorted({value for ion in row["mechanism"]["ions"] for value in ion["read"]})
    ion_writes = sorted({value for ion in row["mechanism"]["ions"] for value in ion["write"]})
    evidence = {
        "source_file": row["file"],
        "state_variables": states,
        "assigned_voltage": "v" in assigned,
        "ion_reads": ion_reads,
        "ion_writes": ion_writes,
        "currents": row["mechanism"]["currents"],
        "has_net_receive": "net_receive" in row["executable_blocks"],
        "random_api": sorted(
            set(row["procedures_and_functions"])
            & {"erand", "urand", "setRNG"}
        ),
        "solve_statements": row["integration"]["solve_statements"],
    }
    secondary: list[str] = []
    if name in VOLTAGE_GATED:
        primary = "voltage_dependent_gate"
        rationale = "Dynamic gate STATE is driven by membrane voltage and controls a membrane current."
    elif name in CALCIUM_GATED:
        primary = "calcium_dependent_gate"
        rationale = "Dynamic gate STATE reads intracellular calcium and controls potassium current."
    elif name in CONCENTRATION_DYNAMICS:
        primary = "ion_concentration_dynamics"
        rationale = "STATE is an ionic concentration updated from an ionic current and written through USEION."
    elif name in EVENT_DRIVEN_SYNAPSES:
        primary = "event_driven_synapse"
        secondary.extend(["synaptic_conductance_dynamics", "stochastic_release"])
        rationale = "NET_RECEIVE changes synaptic state; an explicit random API controls probabilistic release/recovery."
        if "NMDA" in name:
            secondary.append("voltage_dependent_nmda_current")
    elif name in ANALYTIC_POINT_PROCESSES:
        primary = "prescribed_time_dependent_point_process"
        rationale = "POINT_PROCESS current is prescribed analytically from time and parameters, without NET_RECEIVE or STATE."
    else:
        raise ValueError(f"unclassified NMODL mechanism: {name}")
    return {
        "id": f"nmodl:{name}",
        "name": name,
        "source_kind": "nmodl",
        "primary_family": primary,
        "secondary_families": sorted(secondary),
        "rationale": rationale,
        "evidence": evidence,
    }


def _implicit_mechanisms() -> list[dict[str, Any]]:
    return [
        {
            "id": "neuron-runtime:passive-membrane",
            "name": "Passive membrane",
            "source_kind": "neuron_runtime",
            "primary_family": "passive_membrane",
            "secondary_families": [],
            "rationale": "Membrane capacitance and passive/leak terms are part of the compartment membrane equation, not a dedicated file in the teacher mods directory.",
            "evidence": {"contract": "C_m dV/dt plus passive membrane current", "nmodl_file": None},
        },
        {
            "id": "neuron-runtime:axial-coupling",
            "name": "Axial coupling",
            "source_kind": "neuron_runtime",
            "primary_family": "axial_coupling",
            "secondary_families": ["morphology_dependent_cable_dynamics"],
            "rationale": "Inter-segment current is generated by NEURON's cable equation from morphology, Ra and topology, not by a density mechanism file.",
            "evidence": {"contract": "tree topology, segment geometry and axial resistance", "nmodl_file": None},
        },
    ]


def validate_classification(classification: dict[str, Any], inventory: dict[str, Any]) -> dict[str, Any]:
    rows = classification["mechanisms"]
    by_name = {row["name"]: row for row in rows if row["source_kind"] == "nmodl"}
    inventory_names = {row["mechanism"]["name"] for row in inventory["mechanisms"]}
    failures: list[str] = []
    if set(by_name) != inventory_names:
        failures.append("NMODL coverage differs from Task 0.1 inventory")
    for name in EVENT_DRIVEN_SYNAPSES:
        row = by_name.get(name, {})
        if not row.get("evidence", {}).get("has_net_receive"):
            failures.append(f"{name}: event-driven classification lacks NET_RECEIVE evidence")
        if "stochastic_release" not in row.get("secondary_families", []):
            failures.append(f"{name}: stochastic-release family missing")
        if not row.get("evidence", {}).get("random_api"):
            failures.append(f"{name}: stochastic-release classification lacks random API")
    for name in CALCIUM_GATED:
        if "cai" not in by_name[name]["evidence"]["ion_reads"]:
            failures.append(f"{name}: calcium-dependent gate does not read cai")
    for name in VOLTAGE_GATED:
        if not by_name[name]["evidence"]["assigned_voltage"]:
            failures.append(f"{name}: voltage-dependent gate lacks assigned v evidence")
    for name in CONCENTRATION_DYNAMICS:
        if "cai" not in by_name[name]["evidence"]["ion_writes"]:
            failures.append(f"{name}: concentration dynamics does not write cai")
    families = {row["primary_family"] for row in rows}
    required = {
        "voltage_dependent_gate", "calcium_dependent_gate", "ion_concentration_dynamics",
        "passive_membrane", "event_driven_synapse", "axial_coupling",
    }
    if not required <= families:
        failures.append(f"missing required families: {sorted(required - families)}")
    return {
        "valid": not failures,
        "failures": failures,
        "nmodl_coverage": len(by_name),
        "inventory_nmodl_count": len(inventory_names),
        "implicit_mechanism_count": sum(row["source_kind"] != "nmodl" for row in rows),
    }


def build_causal_classification(inventory: dict[str, Any]) -> dict[str, Any]:
    mechanisms = [_classify_mod(row) for row in inventory["mechanisms"]] + _implicit_mechanisms()
    family_counts = Counter(row["primary_family"] for row in mechanisms)
    secondary_counts = Counter(family for row in mechanisms for family in row["secondary_families"])
    result = {
        "schema_version": "giada-teacher-causal-classification-v1",
        "task": "0.2",
        "input_inventory_schema": inventory["schema_version"],
        "input_inventory_sha256": hashlib.sha256(
            json.dumps(inventory, sort_keys=True, ensure_ascii=False).encode("utf-8")
        ).hexdigest(),
        "teacher_commit": inventory["teacher_commit"],
        "classification_policy": {
            "multi_label": True,
            "primary_family_is_exclusive": True,
            "secondary_families_capture_composed_behavior": True,
            "runtime_mechanisms_may_lack_nmodl_files": True,
            "neural_replacement_strategy_deferred": True,
        },
        "summary": {
            "mechanism_count": len(mechanisms),
            "nmodl_mechanism_count": len(inventory["mechanisms"]),
            "implicit_runtime_mechanism_count": 2,
            "primary_family_counts": dict(sorted(family_counts.items())),
            "secondary_family_counts": dict(sorted(secondary_counts.items())),
        },
        "mechanisms": mechanisms,
    }
    result["validation"] = validate_classification(result, inventory)
    if not result["validation"]["valid"]:
        raise ValueError(f"causal classification failed validation: {result['validation']['failures']}")
    return result


def write_causal_classification(result: dict[str, Any], json_path: str | Path, markdown_path: str | Path) -> None:
    json_path, markdown_path = Path(json_path), Path(markdown_path)
    json_path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    lines = [
        "# GIADA teacher causal mechanism classification", "",
        f"- Teacher commit: `{result['teacher_commit']}`",
        f"- NMODL mechanisms: **{result['summary']['nmodl_mechanism_count']}**",
        f"- Runtime mechanisms made explicit: **{result['summary']['implicit_runtime_mechanism_count']}**", "",
        "| Mechanism | Primary causal family | Secondary behavior | Evidence |",
        "|---|---|---|---|",
    ]
    for row in result["mechanisms"]:
        evidence = row["evidence"]
        compact = []
        if evidence.get("state_variables"):
            compact.append("STATE=" + ",".join(evidence["state_variables"]))
        if evidence.get("assigned_voltage"):
            compact.append("v")
        if evidence.get("ion_reads"):
            compact.append("READ=" + ",".join(evidence["ion_reads"]))
        if evidence.get("ion_writes"):
            compact.append("WRITE=" + ",".join(evidence["ion_writes"]))
        if evidence.get("has_net_receive"):
            compact.append("NET_RECEIVE")
        if evidence.get("random_api"):
            compact.append("RNG=" + ",".join(evidence["random_api"]))
        if evidence.get("contract"):
            compact.append(evidence["contract"])
        lines.append(
            f"| `{row['name']}` | `{row['primary_family']}` | "
            f"{', '.join(row['secondary_families']) or '—'} | {'; '.join(compact) or '—'} |"
        )
    lines += ["", "## Methodological boundary", "", "This taxonomy identifies causal subsystem families. It does not yet define the minimal atomic data contract or select a neural architecture; those decisions belong to Task 0.3 and later tasks.", ""]
    markdown_path.write_text("\n".join(lines), encoding="utf-8")
